// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Messages sent from client to server over WebSocket.
 */
export type WsClientMsg = { "type": "BuzzIn", team_index: number, client_timestamp: string, } | { "type": "ReleaseBuzz" } | { "type": "LockBuzzers" } | { "type": "UpdateScore", team_index: number, score: number, } | { "type": "UpdateTeamName", team_index: number, name: string, } | { "type": "UpdateDarkMode", enabled: boolean, } | { "type": "UpdateTimerEnabled", enabled: boolean, } | { "type": "AddTeam" } | { "type": "RemoveTeam", team_index: number, } | { "type": "ResetHasBuzzed" } | { "type": "SetPage", page: string, } | { "type": "Ping", client_timestamp: string, };
