// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";
import type { Team } from "./Team";

/**
 * Messages sent from server to client over WebSocket.
 */
export type WsServerMsg = { "type": "FullState", session: Session, } | { "type": "BuzzLocked", team_index: number, server_timestamp: string, client_timestamp: string, team_name: string, } | { "type": "BuzzersLocked" } | { "type": "BuzzReleased" } | { "type": "ScoreUpdate", team_index: number, score: number, } | { "type": "TeamNameUpdate", team_index: number, name: string, } | { "type": "DarkModeUpdate", enabled: boolean, } | { "type": "TimerEnabledUpdate", enabled: boolean, } | { "type": "TeamAdded", team: Team, } | { "type": "TeamRemoved", team_index: number, } | { "type": "HasBuzzedReset" } | { "type": "PageUpdate", page: string, } | { "type": "SessionClosed" } | { "type": "Pong", server_timestamp: string, client_timestamp: string, };
